changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat

  categories:
    - title: Exciting New Features 🎉
      labels:
        - type/enhancement
        - type/feature
    - title: Other Changes
      labels:
        - "*"
