---
name: "faunadb"
version: 0.0.1
resources:
  "faunadb:database:Database":
    properties:
      name:
        type: string
      url:
        type: string
    required:
      - name
      - url
    inputProperties:
      name:
        type: string
      region:
        type: string
        enum:
          - Classic
          - EU
          - US
    requiredInputs:
      - name
      - region
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
  go:
    generateResourceContainerTypes: true
    importBasePath: "github.com/rawkode/pulumi-faunadb/sdk/go/faunadb"
  nodejs:
    dependencies:
      "@pulumi/pulumi": "^3.0.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
