name: release
on:
  push:
    tags:
      - v*.*.*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish_binary:
    name: Publish Provider Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.1.0
        with:
          repo: pulumi/pulumictl

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1

      - run: make build_provider

      - name: Create Provider Binaries
        run: make dist

      - name: Create GH Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
